services:
    bugbuster.stardatebundle.initialize:
        class: BugBuster\StardateBundle\EventListener\System
        tags:
            - { name: contao.hook, hook: initializeSystem, method: initializeSystem, priority: -256 }
        arguments:
            - "@request_stack"
            - "@contao.routing.scope_matcher"