services:
    _defaults: { autowire: true, autoconfigure: true, public: false }
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    BugBuster\StardateBundle\Controller\ContentElement\StardateController:
        public: true
        tags:
            -
                name: contao.content_element
                category: texts