services:

    bugbuster.stardatebundle.insert_tags:
        class: BugBuster\StardateBundle\EventListener\InsertTagsListener
        tags:
            - { name: contao.hook, hook: replaceInsertTags, method: onReplaceInsertTags }
        arguments:
            - '@contao.framework'
        public: true
