services:
    _defaults: { autowire: true, autoconfigure: true, public: false }

    BugBuster\StardateBundle\Controller\ContentElement\StardateController:
        public: true
        tags:
            -
                name: contao.content_element
                category: texts